/****** Object:  Table [dbo].[FORECAST_AUDIT]    Script Date: 13/4/2022 4:32:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORECAST_AUDIT](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUID_PROJECT] [uniqueidentifier] NOT NULL,
	[DATA_DATE] [datetime] NOT NULL,
	[COMMENTS] [nvarchar](500) NULL,
	[CREATED] [datetime] NOT NULL,
	[CREATEDBY] [uniqueidentifier] NOT NULL,
	[UPDATED] [datetime] NULL,
	[UPDATEDBY] [uniqueidentifier] NULL,
	[DELETED] [datetime] NULL,
	[DELETEDBY] [uniqueidentifier] NULL,
 CONSTRAINT [PK_FORECAST_AUDIT] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FORECAST_AUDIT]  WITH CHECK ADD  CONSTRAINT [FK_FORECAST_AUDIT_PROJECT] FOREIGN KEY([GUID_PROJECT])
REFERENCES [dbo].[PROJECT] ([GUID])
GO

ALTER TABLE [dbo].[FORECAST_AUDIT] CHECK CONSTRAINT [FK_FORECAST_AUDIT_PROJECT]
GO

/****** Object:  Table [dbo].[FORECAST_JOB_AUDIT]    Script Date: 13/4/2022 4:33:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORECAST_JOB_AUDIT](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUID_FORECAST_AUDIT] [uniqueidentifier] NOT NULL,
	[GUID_FORECAST_JOB] [uniqueidentifier] NOT NULL,
	[SUBJOB_CODE] [nvarchar](50) NOT NULL,
	[DISCIPLINE_CODE] [nvarchar](50) NOT NULL,
	[COMMODITY_CODE] [nvarchar](50) NOT NULL,
	[VARIATION_CODE] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[REFERENCE] [nvarchar](500) NULL,
	[NOTE] [nvarchar](500) NULL,
	[UOM] [nvarchar](50) NULL,
	[DATA_DATE] [datetime] NOT NULL,
	[FORECAST_RATE] [decimal](18, 2) NULL,
	[CREATED] [datetime] NOT NULL,
	[CREATEDBY] [uniqueidentifier] NOT NULL,
	[UPDATED] [datetime] NULL,
	[UPDATEDBY] [uniqueidentifier] NULL,
	[DELETED] [datetime] NULL,
	[DELETEDBY] [uniqueidentifier] NULL,
	[STOCK_ITEM] [nvarchar](50) NULL,
	[IS_FLOATING_RATE] [bit] NOT NULL,
	[DELETE_REASON] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_FORECAST_JOB_AUDIT] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FORECAST_JOB_AUDIT] ADD  CONSTRAINT [DF_FORECAST_JOB_AUDIT_VARIATION_CODE]  DEFAULT ('') FOR [VARIATION_CODE]
GO

ALTER TABLE [dbo].[FORECAST_JOB_AUDIT] ADD  CONSTRAINT [DF_FORECAST_JOB_AUDIT_IS_FLOATING_RATE]  DEFAULT ((0)) FOR [IS_FLOATING_RATE]
GO

ALTER TABLE [dbo].[FORECAST_JOB_AUDIT] ADD  CONSTRAINT [DF_FORECAST_JOB_AUDIT_DELETE_REASON]  DEFAULT ('') FOR [DELETE_REASON]
GO

ALTER TABLE [dbo].[FORECAST_JOB_AUDIT]  WITH CHECK ADD  CONSTRAINT [FK_FORECAST_JOB_AUDIT_FORECAST_AUDIT] FOREIGN KEY([GUID_FORECAST_AUDIT])
REFERENCES [dbo].[FORECAST_AUDIT] ([GUID])
GO

ALTER TABLE [dbo].[FORECAST_JOB_AUDIT] CHECK CONSTRAINT [FK_FORECAST_JOB_AUDIT_FORECAST_AUDIT]
GO

/****** Object:  Table [dbo].[FORECAST_JOB_HOUR_AUDIT]    Script Date: 13/4/2022 4:33:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORECAST_JOB_HOUR_AUDIT](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUID_FORECAST_AUDIT] [uniqueidentifier] NOT NULL,
	[GUID_FORECAST_JOB] [uniqueidentifier] NOT NULL,
	[FORECAST_DATE] [datetime] NOT NULL,
	[FORECAST_HOUR] [decimal](18, 2) NULL,
	[CREATED] [datetime] NOT NULL,
	[CREATEDBY] [uniqueidentifier] NOT NULL,
	[UPDATED] [datetime] NULL,
	[UPDATEDBY] [uniqueidentifier] NULL,
	[DELETED] [datetime] NULL,
	[DELETEDBY] [uniqueidentifier] NULL,
 CONSTRAINT [PK_FORECAST_JOB_HOUR_AUDIT] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FORECAST_JOB_HOUR_AUDIT]  WITH CHECK ADD  CONSTRAINT [FK_FORECAST_JOB_HOUR_AUDIT_FORECAST_AUDIT] FOREIGN KEY([GUID_FORECAST_AUDIT])
REFERENCES [dbo].[FORECAST_AUDIT] ([GUID])
GO

ALTER TABLE [dbo].[FORECAST_JOB_HOUR_AUDIT] CHECK CONSTRAINT [FK_FORECAST_JOB_HOUR_AUDIT_FORECAST_AUDIT]
GO

ALTER TABLE [dbo].[FORECAST_JOB_HOUR_AUDIT]  WITH CHECK ADD  CONSTRAINT [FK_FORECAST_JOB_HOUR_AUDIT_FORECAST_JOB_HOUR_AUDIT] FOREIGN KEY([GUID])
REFERENCES [dbo].[FORECAST_JOB_HOUR_AUDIT] ([GUID])
GO

ALTER TABLE [dbo].[FORECAST_JOB_HOUR_AUDIT] CHECK CONSTRAINT [FK_FORECAST_JOB_HOUR_AUDIT_FORECAST_JOB_HOUR_AUDIT]
GO

/****** Object:  StoredProcedure [dbo].[RefreshForecastIndirects]    Script Date: 13/4/2022 3:26:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Su.Bing-Wen
-- Create date: 25/10/2021
-- Description:	Generate forecast budget snapshot
-- =============================================
ALTER PROCEDURE [dbo].[RefreshForecastIndirectsAudit] @PROJECT_NUMBER NVARCHAR(10), @DATA_DATE DATETIME, @USER_GUID UNIQUEIDENTIFIER
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	-- get project guid
	DECLARE @PROJECT_GUID AS UNIQUEIDENTIFIER
	SET @PROJECT_GUID = (SELECT TOP 1 GUID FROM PROJECT WHERE NUMBER = @PROJECT_NUMBER AND DELETED IS NULL)


	
	IF EXISTS (SELECT * FROM FORECAST_AUDIT WHERE GUID_PROJECT = @PROJECT_GUID AND DATA_DATE = @DATA_DATE)
	BEGIN
		UPDATE FORECAST_AUDIT SET UPDATED = GETDATE(), UPDATEDBY = @USER_GUID WHERE GUID_PROJECT = @PROJECT_GUID AND DATA_DATE = @DATA_DATE
	END
	ELSE
	BEGIN
		INSERT INTO FORECAST_AUDIT SELECT NEWID(), @PROJECT_GUID, @DATA_DATE, '', GETDATE(), @USER_GUID, NULL, NULL, NULL, NULL
	END
	
	-- get audit Guid if exists
	DECLARE @FORECAST_AUDIT_GUID AS UNIQUEIDENTIFIER
	SET @FORECAST_AUDIT_GUID = (SELECT GUID FROM FORECAST_AUDIT WHERE GUID_PROJECT = @PROJECT_GUID AND DATA_DATE = @DATA_DATE)

	-- delete the forecast job audit before writing
	DELETE FROM FORECAST_JOB_AUDIT WHERE GUID_FORECAST_AUDIT = @FORECAST_AUDIT_GUID
	
	-- delete the forecast job hour audit before writing
	DELETE FROM FORECAST_JOB_HOUR_AUDIT WHERE GUID_FORECAST_AUDIT = @FORECAST_AUDIT_GUID

	INSERT INTO FORECAST_JOB_AUDIT SELECT NEWID(), @FORECAST_AUDIT_GUID, GUID, SUBJOB_CODE, DISCIPLINE_CODE, COMMODITY_CODE, VARIATION_CODE, DESCRIPTION, 
	REFERENCE, NOTE, UOM, @DATA_DATE, FORECAST_RATE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, DELETED, DELETEDBY, STOCK_ITEM, IS_FLOATING_RATE, DELETE_REASON FROM
	(
		SELECT FORECAST_JOB.*
		FROM FORECAST_JOB
		JOIN FORECAST_JOB_HOUR ON FORECAST_JOB.GUID = FORECAST_JOB_HOUR.GUID_FORECAST_JOB
		WHERE FORECAST_JOB.GUID_PROJECT = @PROJECT_GUID AND FORECAST_JOB.DELETED IS NULL AND FORECAST_JOB_HOUR.DELETED IS NULL AND FORECAST_JOB_HOUR.FORECAST_DATE > @DATA_DATE
	) ForecastJob

	INSERT INTO FORECAST_JOB_HOUR_AUDIT SELECT NEWID(), @FORECAST_AUDIT_GUID, GUID_FORECAST_JOB, FORECAST_DATE, FORECAST_HOUR, CREATED, CREATEDBY, UPDATED, UPDATEDBY, DELETED, DELETEDBY FROM
	(
		SELECT FORECAST_JOB_HOUR.*
		FROM FORECAST_JOB_HOUR
		JOIN FORECAST_JOB ON FORECAST_JOB.GUID = FORECAST_JOB_HOUR.GUID_FORECAST_JOB
		WHERE FORECAST_JOB.GUID_PROJECT = @PROJECT_GUID AND FORECAST_JOB.DELETED IS NULL AND FORECAST_JOB_HOUR.DELETED IS NULL AND FORECAST_JOB_HOUR.FORECAST_DATE > @DATA_DATE
	) ForecastJobHour
END

