//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BluePrintsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BluePrintsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.BluePrintsResources", typeof(BluePrintsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I1.
        /// </summary>
        internal static string Alternate_Design_Phase {
            get {
                return ResourceManager.GetString("Alternate_Design_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation_Caption {
            get {
                return ResourceManager.GetString("Confirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this {0}?.
        /// </summary>
        internal static string Confirmation_Delete {
            get {
                return ResourceManager.GetString("Confirmation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to reload the entity and lose unsaved changes. Click Cancel to continue editing data..
        /// </summary>
        internal static string Confirmation_Reset {
            get {
                return ResourceManager.GetString("Confirmation_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset layout? Reopen this view for the new layout to take effect..
        /// </summary>
        internal static string Confirmation_ResetLayout {
            get {
                return ResourceManager.GetString("Confirmation_ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string Confirmation_Save {
            get {
                return ResourceManager.GetString("Confirmation_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to save the parent {0} entity before adding a new record. Do you want to save it now?.
        /// </summary>
        internal static string Confirmation_SaveParent {
            get {
                return ResourceManager.GetString("Confirmation_SaveParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p4y57zcvp.
        /// </summary>
        internal static string Default_AdminPassword {
            get {
                return ResourceManager.GetString("Default_AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to superadmin.
        /// </summary>
        internal static string Default_AdminUsername {
            get {
                return ResourceManager.GetString("Default_AdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        internal static string Default_Area {
            get {
                return ResourceManager.GetString("Default_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSTRUCTION.
        /// </summary>
        internal static string Default_Construction_Department {
            get {
                return ResourceManager.GetString("Default_Construction_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        internal static string Default_Construction_Phase {
            get {
                return ResourceManager.GetString("Default_Construction_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D1.
        /// </summary>
        internal static string Default_Design_Phase {
            get {
                return ResourceManager.GetString("Default_Design_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string Default_New_Project_Department {
            get {
                return ResourceManager.GetString("Default_New_Project_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Engineering.
        /// </summary>
        internal static string Default_New_Project_Discipline {
            get {
                return ResourceManager.GetString("Default_New_Project_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Default_New_Project_DocType {
            get {
                return ResourceManager.GetString("Default_New_Project_DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCUREMENT.
        /// </summary>
        internal static string Default_Procurement_Department {
            get {
                return ResourceManager.GetString("Default_Procurement_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Default_Register_Numeric_Length {
            get {
                return ResourceManager.GetString("Default_Register_Numeric_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41000.
        /// </summary>
        internal static string Default_Revenue_StockCode {
            get {
                return ResourceManager.GetString("Default_Revenue_StockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lhpwrma6!.
        /// </summary>
        internal static string Default_SecurityKey {
            get {
                return ResourceManager.GetString("Default_SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        internal static string Default_Sub_Area {
            get {
                return ResourceManager.GetString("Default_Sub_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BluePrints.
        /// </summary>
        internal static string Default_XML_Directory {
            get {
                return ResourceManager.GetString("Default_XML_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.config.
        /// </summary>
        internal static string Default_XML_Filename {
            get {
                return ResourceManager.GetString("Default_XML_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @primerogroup.com.au.
        /// </summary>
        internal static string DefaultAuthenticateDomain {
            get {
                return ResourceManager.GetString("DefaultAuthenticateDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @primero.com.au.
        /// </summary>
        internal static string DefaultMailDomain {
            get {
                return ResourceManager.GetString("DefaultMailDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Entity_Changed {
            get {
                return ResourceManager.GetString("Entity_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Deleted).
        /// </summary>
        internal static string Entity_Deleted {
            get {
                return ResourceManager.GetString("Entity_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        internal static string Entity_New {
            get {
                return ResourceManager.GetString("Entity_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataService Request Error.
        /// </summary>
        internal static string Exception_DataServiceRequestErrorCaption {
            get {
                return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        internal static string Exception_UpdateErrorCaption {
            get {
                return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string Exception_ValidationErrorCaption {
            get {
                return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string GlobalOffice {
            get {
                return ResourceManager.GetString("GlobalOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health check completed without any issues.
        /// </summary>
        internal static string Notify_HealthCheck_OK {
            get {
                return ResourceManager.GetString("Notify_HealthCheck_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 units populated.
        /// </summary>
        internal static string Notify_P6_Assignment_Write_Complete {
            get {
                return ResourceManager.GetString("Notify_P6_Assignment_Write_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View has been refreshed because of changes to.
        /// </summary>
        internal static string Notify_Refresh {
            get {
                return ResourceManager.GetString("Notify_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server: Application closed..
        /// </summary>
        internal static string Notify_SignalR_CloseApplication {
            get {
                return ResourceManager.GetString("Notify_SignalR_CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server: Start server before connecting clients..
        /// </summary>
        internal static string Notify_SignalR_UnableToConnect {
            get {
                return ResourceManager.GetString("Notify_SignalR_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add this record first before adjusting it&apos;s units.
        /// </summary>
        internal static string Notify_VariationNewRowError {
            get {
                return ResourceManager.GetString("Notify_VariationNewRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed, this view can&apos;t be accessed until it is restored.
        /// </summary>
        internal static string Notify_View_Removed {
            get {
                return ResourceManager.GetString("Notify_View_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been restored.
        /// </summary>
        internal static string Notify_View_Restored {
            get {
                return ResourceManager.GetString("Notify_View_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 progress schedule population failed.
        /// </summary>
        internal static string P6_Assignment_Progress_Write_Failed {
            get {
                return ResourceManager.GetString("P6_Assignment_Progress_Write_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 progress schedule successfully populated.
        /// </summary>
        internal static string P6_Assignment_Progress_Write_Success {
            get {
                return ResourceManager.GetString("P6_Assignment_Progress_Write_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 units populated.
        /// </summary>
        internal static string P6_Assignment_Units_Populated {
            get {
                return ResourceManager.GetString("P6_Assignment_Units_Populated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorised.
        /// </summary>
        internal static string UncategorisedStockCode {
            get {
                return ResourceManager.GetString("UncategorisedStockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Value_Any {
            get {
                return ResourceManager.GetString("Value_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning_Caption {
            get {
                return ResourceManager.GetString("Warning_Caption", resourceCulture);
            }
        }
    }
}
