//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BluePrintsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BluePrintsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.BluePrintsResources", typeof(BluePrintsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select objects to add.
        /// </summary>
        internal static string AddRemoveDetailEntities_SelectObjects {
            get {
                return ResourceManager.GetString("AddRemoveDetailEntities_SelectObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p4y57zcvp.
        /// </summary>
        internal static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to superadmin.
        /// </summary>
        internal static string AdminUsername {
            get {
                return ResourceManager.GetString("AdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Commodity.
        /// </summary>
        internal static string CommodityCode_NewCommodity {
            get {
                return ResourceManager.GetString("CommodityCode_NewCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add departments before adding commodity code.
        /// </summary>
        internal static string CommodityCode_NoDepartment {
            get {
                return ResourceManager.GetString("CommodityCode_NoDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add disciplines before adding commodity code.
        /// </summary>
        internal static string CommodityCode_NoDiscipline {
            get {
                return ResourceManager.GetString("CommodityCode_NoDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Commodity_Code&gt;.
        /// </summary>
        internal static string CommodityCodeGroup_Generated {
            get {
                return ResourceManager.GetString("CommodityCodeGroup_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string CommodityCodeGroup_New {
            get {
                return ResourceManager.GetString("CommodityCodeGroup_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add commodity under commodity.
        /// </summary>
        internal static string CommodityGroup_CannotAddChild {
            get {
                return ResourceManager.GetString("CommodityGroup_CannotAddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change WBS into commodity.
        /// </summary>
        internal static string CommodityGroup_CannotAssignCommodity {
            get {
                return ResourceManager.GetString("CommodityGroup_CannotAssignCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign parent commodity code.
        /// </summary>
        internal static string CommodityGroup_CannotSelectParent {
            get {
                return ResourceManager.GetString("CommodityGroup_CannotSelectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity code is required.
        /// </summary>
        internal static string CommodityGroup_MustSelectCommodity {
            get {
                return ResourceManager.GetString("CommodityGroup_MustSelectCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation_Caption {
            get {
                return ResourceManager.GetString("Confirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this {0}?.
        /// </summary>
        internal static string Confirmation_Delete {
            get {
                return ResourceManager.GetString("Confirmation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to reload the entity and lose unsaved changes. Click Cancel to continue editing data..
        /// </summary>
        internal static string Confirmation_Reset {
            get {
                return ResourceManager.GetString("Confirmation_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset layout? Reopen this view for the new layout to take effect..
        /// </summary>
        internal static string Confirmation_ResetLayout {
            get {
                return ResourceManager.GetString("Confirmation_ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string Confirmation_Save {
            get {
                return ResourceManager.GetString("Confirmation_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to save the parent {0} entity before adding a new record. Do you want to save it now?.
        /// </summary>
        internal static string Confirmation_SaveParent {
            get {
                return ResourceManager.GetString("Confirmation_SaveParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DataPointsBuilder_MaxProjectDuration {
            get {
                return ResourceManager.GetString("DataPointsBuilder_MaxProjectDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSTRUCTION.
        /// </summary>
        internal static string DefaultConstructionDepartment {
            get {
                return ResourceManager.GetString("DefaultConstructionDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Entity_Changed {
            get {
                return ResourceManager.GetString("Entity_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Deleted).
        /// </summary>
        internal static string Entity_Deleted {
            get {
                return ResourceManager.GetString("Entity_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        internal static string Entity_New {
            get {
                return ResourceManager.GetString("Entity_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create custom project commodity code, do you want to continue?.
        /// </summary>
        internal static string Estimation_Item_Direct_AddCustomCommodityGroup {
            get {
                return ResourceManager.GetString("Estimation_Item_Direct_AddCustomCommodityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select yes to edit current project specific commodity code or no to edit others.
        /// </summary>
        internal static string Estimation_Item_Direct_EditCurrentOrOther {
            get {
                return ResourceManager.GetString("Estimation_Item_Direct_EditCurrentOrOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select yes to edit current project specific commodity code or no to add a new one.
        /// </summary>
        internal static string Estimation_Item_Direct_EditOrAddNewCommodityCode {
            get {
                return ResourceManager.GetString("Estimation_Item_Direct_EditOrAddNewCommodityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project specific commodity code created.
        /// </summary>
        internal static string Estimation_Item_Direct_ProjectSpecificCommodityCodeCreated {
            get {
                return ResourceManager.GetString("Estimation_Item_Direct_ProjectSpecificCommodityCodeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataService Request Error.
        /// </summary>
        internal static string Exception_DataServiceRequestErrorCaption {
            get {
                return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        internal static string Exception_UpdateErrorCaption {
            get {
                return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string Exception_ValidationErrorCaption {
            get {
                return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string NewProject_DefaultDepartment {
            get {
                return ResourceManager.GetString("NewProject_DefaultDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Engineering.
        /// </summary>
        internal static string NewProject_DefaultDiscipline {
            get {
                return ResourceManager.GetString("NewProject_DefaultDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string NewProject_DefaultDocType {
            get {
                return ResourceManager.GetString("NewProject_DefaultDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add this record first before adjusting it&apos;s units.
        /// </summary>
        internal static string Notify_AddBASELINE_ITEMBeforeVARIATION_UNITS {
            get {
                return ResourceManager.GetString("Notify_AddBASELINE_ITEMBeforeVARIATION_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed, this view can&apos;t be accessed until it is restored.
        /// </summary>
        internal static string Notify_View_Removed {
            get {
                return ResourceManager.GetString("Notify_View_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been restored.
        /// </summary>
        internal static string Notify_View_Restored {
            get {
                return ResourceManager.GetString("Notify_View_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string ProgressReporting_DefaultHoursADay {
            get {
                return ResourceManager.GetString("ProgressReporting_DefaultHoursADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View has been refreshed because of changes to.
        /// </summary>
        internal static string Refresh_Notify {
            get {
                return ResourceManager.GetString("Refresh_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lhpwrma6!.
        /// </summary>
        internal static string SecurityKey {
            get {
                return ResourceManager.GetString("SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server: Application closed..
        /// </summary>
        internal static string SignalR_CloseApplication {
            get {
                return ResourceManager.GetString("SignalR_CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server: Start server before connecting clients..
        /// </summary>
        internal static string SignalR_UnableToConnect {
            get {
                return ResourceManager.GetString("SignalR_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning_Caption {
            get {
                return ResourceManager.GetString("Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields contain invalid data. Click OK to close the page and lose unsaved changes. Press Cancel to continue editing data..
        /// </summary>
        internal static string Warning_SomeFieldsContainInvalidData {
            get {
                return ResourceManager.GetString("Warning_SomeFieldsContainInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 progress schedule population failed.
        /// </summary>
        internal static string WORKPACK_ASSIGNMENT_P6ProgressWriteFailed {
            get {
                return ResourceManager.GetString("WORKPACK_ASSIGNMENT_P6ProgressWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 progress schedule successfully populated.
        /// </summary>
        internal static string WORKPACK_ASSIGNMENT_P6ProgressWriteSuccess {
            get {
                return ResourceManager.GetString("WORKPACK_ASSIGNMENT_P6ProgressWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6 units populated.
        /// </summary>
        internal static string WORKPACK_ASSIGNMENT_P6WriteComplete {
            get {
                return ResourceManager.GetString("WORKPACK_ASSIGNMENT_P6WriteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change the internal name too?.
        /// </summary>
        internal static string WORKPACK_InternalNameChange {
            get {
                return ResourceManager.GetString("WORKPACK_InternalNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BluePrints.
        /// </summary>
        internal static string XMLDefaultDirectory {
            get {
                return ResourceManager.GetString("XMLDefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.config.
        /// </summary>
        internal static string XMLFilename {
            get {
                return ResourceManager.GetString("XMLFilename", resourceCulture);
            }
        }
    }
}
