//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColumnHeaderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColumnHeaderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.ColumnHeaderResources", typeof(ColumnHeaderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string AreaHeaderString {
            get {
                return ResourceManager.GetString("AreaHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Number.
        /// </summary>
        internal static string ClientNumberHeaderString {
            get {
                return ResourceManager.GetString("ClientNumberHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string CommentsHeaderString {
            get {
                return ResourceManager.GetString("CommentsHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current %.
        /// </summary>
        internal static string CurrentPercentageHeaderString {
            get {
                return ResourceManager.GetString("CurrentPercentageHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverable Type.
        /// </summary>
        internal static string DeliverableTypeHeaderString {
            get {
                return ResourceManager.GetString("DeliverableTypeHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DepartmentHeaderString {
            get {
                return ResourceManager.GetString("DepartmentHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        internal static string DisciplineHeaderString {
            get {
                return ResourceManager.GetString("DisciplineHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline Number.
        /// </summary>
        internal static string DisciplineNumberHeaderString {
            get {
                return ResourceManager.GetString("DisciplineNumberHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string DocumentTypeHeaderString {
            get {
                return ResourceManager.GetString("DocumentTypeHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Number.
        /// </summary>
        internal static string InternalNumberHeaderString {
            get {
                return ResourceManager.GetString("InternalNumberHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string OfficeHeaderString {
            get {
                return ResourceManager.GetString("OfficeHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string PhaseHeaderString {
            get {
                return ResourceManager.GetString("PhaseHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Title.
        /// </summary>
        internal static string PrimaryTitleHeaderString {
            get {
                return ResourceManager.GetString("PrimaryTitleHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string ResourceHeaderString {
            get {
                return ResourceManager.GetString("ResourceHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Title.
        /// </summary>
        internal static string SecondaryTitleHeaderString {
            get {
                return ResourceManager.GetString("SecondaryTitleHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Area.
        /// </summary>
        internal static string SubAreaHeaderString {
            get {
                return ResourceManager.GetString("SubAreaHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Job.
        /// </summary>
        internal static string SubJobHeaderString {
            get {
                return ResourceManager.GetString("SubJobHeaderString", resourceCulture);
            }
        }
    }
}
