//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NavigationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.NavigationResources", typeof(NavigationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active projects category.
        /// </summary>
        internal static string Category_ActiveProjects {
            get {
                return ResourceManager.GetString("Category_ActiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data category menu.
        /// </summary>
        internal static string Category_Data {
            get {
                return ResourceManager.GetString("Category_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exo data category.
        /// </summary>
        internal static string Category_Data_EXO {
            get {
                return ResourceManager.GetString("Category_Data_EXO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead projects category.
        /// </summary>
        internal static string Category_LeadProjects {
            get {
                return ResourceManager.GetString("Category_LeadProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construct category.
        /// </summary>
        internal static string Category_Project_Construct {
            get {
                return ResourceManager.GetString("Category_Project_Construct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction progress category.
        /// </summary>
        internal static string Category_Project_Construct_Progress {
            get {
                return ResourceManager.GetString("Category_Project_Construct_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construct rates category.
        /// </summary>
        internal static string Category_Project_Construct_Rate {
            get {
                return ResourceManager.GetString("Category_Project_Construct_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design category.
        /// </summary>
        internal static string Category_Project_Design {
            get {
                return ResourceManager.GetString("Category_Project_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design rates category.
        /// </summary>
        internal static string Category_Project_Design_Rate {
            get {
                return ResourceManager.GetString("Category_Project_Design_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project EXO data maintenance category.
        /// </summary>
        internal static string Category_Project_EXO {
            get {
                return ResourceManager.GetString("Category_Project_EXO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project forecast category.
        /// </summary>
        internal static string Category_Project_Forecast {
            get {
                return ResourceManager.GetString("Category_Project_Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project registers category.
        /// </summary>
        internal static string Category_Register {
            get {
                return ResourceManager.GetString("Category_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock group category.
        /// </summary>
        internal static string Category_StockGroup {
            get {
                return ResourceManager.GetString("Category_StockGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted tender category.
        /// </summary>
        internal static string Category_SubmittedProjects {
            get {
                return ResourceManager.GetString("Category_SubmittedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised category.
        /// </summary>
        internal static string Category_Unauthorised {
            get {
                return ResourceManager.GetString("Category_Unauthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User project category.
        /// </summary>
        internal static string Category_UserProjects {
            get {
                return ResourceManager.GetString("Category_UserProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User tendering project category.
        /// </summary>
        internal static string Category_UserTenders {
            get {
                return ResourceManager.GetString("Category_UserTenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in progress category.
        /// </summary>
        internal static string Category_WIPProjects {
            get {
                return ResourceManager.GetString("Category_WIPProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project area right click context menu.
        /// </summary>
        internal static string ContextMenu_ProjectAreas {
            get {
                return ResourceManager.GetString("ContextMenu_ProjectAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project baselines right click context menu.
        /// </summary>
        internal static string ContextMenu_ProjectBaselines {
            get {
                return ResourceManager.GetString("ContextMenu_ProjectBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project estimates right click context menu.
        /// </summary>
        internal static string ContextMenu_ProjectEstimates {
            get {
                return ResourceManager.GetString("ContextMenu_ProjectEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project progresses right click context menu.
        /// </summary>
        internal static string ContextMenu_ProjectProgresses {
            get {
                return ResourceManager.GetString("ContextMenu_ProjectProgresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup change log information view.
        /// </summary>
        internal static string Global_ChangeLog {
            get {
                return ResourceManager.GetString("Global_ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main project menu.
        /// </summary>
        internal static string Menu_AllProjects {
            get {
                return ResourceManager.GetString("Menu_AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All project P&amp;L.
        /// </summary>
        internal static string Menu_AllProjects_PL {
            get {
                return ResourceManager.GetString("Menu_AllProjects_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client maintenance menu.
        /// </summary>
        internal static string Menu_Client {
            get {
                return ResourceManager.GetString("Menu_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity code maintenance menu.
        /// </summary>
        internal static string Menu_CommodityCode {
            get {
                return ResourceManager.GetString("Menu_CommodityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard menu.
        /// </summary>
        internal static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department maintenance menu.
        /// </summary>
        internal static string Menu_Departments {
            get {
                return ResourceManager.GetString("Menu_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline maintenance menu.
        /// </summary>
        internal static string Menu_Disciplines {
            get {
                return ResourceManager.GetString("Menu_Disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document control menu.
        /// </summary>
        internal static string Menu_DocumentControl {
            get {
                return ResourceManager.GetString("Menu_DocumentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document types maintenance menu.
        /// </summary>
        internal static string Menu_DocumentTypes {
            get {
                return ResourceManager.GetString("Menu_DocumentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXO Job Resource maintenance menu.
        /// </summary>
        internal static string Menu_EXO_JobResources {
            get {
                return ResourceManager.GetString("Menu_EXO_JobResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXO Stock Items maintenance menu.
        /// </summary>
        internal static string Menu_EXO_StockItems {
            get {
                return ResourceManager.GetString("Menu_EXO_StockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXO users maintenance menu.
        /// </summary>
        internal static string Menu_EXO_Users {
            get {
                return ResourceManager.GetString("Menu_EXO_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company wide HSE menu.
        /// </summary>
        internal static string Menu_HSE {
            get {
                return ResourceManager.GetString("Menu_HSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting actions maintenance menu.
        /// </summary>
        internal static string Menu_MeetingActions {
            get {
                return ResourceManager.GetString("Menu_MeetingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office maintenance menu.
        /// </summary>
        internal static string Menu_Offices {
            get {
                return ResourceManager.GetString("Menu_Offices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases maintenance menu.
        /// </summary>
        internal static string Menu_Phases {
            get {
                return ResourceManager.GetString("Menu_Phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project areas menu.
        /// </summary>
        internal static string Menu_Project_Areas {
            get {
                return ResourceManager.GetString("Menu_Project_Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction direct charge rate maintenance.
        /// </summary>
        internal static string Menu_Project_ConstructionDirectChargeRate {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionDirectChargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction direct cost rate maintenance.
        /// </summary>
        internal static string Menu_Project_ConstructionDirectCostRate {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionDirectCostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction indirect charge rate maintenance.
        /// </summary>
        internal static string Menu_Project_ConstructionIndirectChargeRate {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionIndirectChargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction indirect cost rate maintenance.
        /// </summary>
        internal static string Menu_Project_ConstructionIndirectCostRate {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionIndirectCostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction job setup maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructionJobs {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction resource allocation menu.
        /// </summary>
        internal static string Menu_Project_ConstructionResourceAllocation {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionResourceAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction stage maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructionStage {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction variation maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructionVariation {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructionVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project construction progress maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructProgress_Concrete {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructProgress_Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project electrical construction progress maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructProgress_Electrical {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructProgress_Electrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project mechanical construction progress maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructProgress_Mechanical {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructProgress_Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project piping construction progress maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructProgress_Piping {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructProgress_Piping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project structural construction progress maintenance menu.
        /// </summary>
        internal static string Menu_Project_ConstructProgress_Structural {
            get {
                return ResourceManager.GetString("Menu_Project_ConstructProgress_Structural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project dashboard menu.
        /// </summary>
        internal static string Menu_Project_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Project_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design deliverables maintenance menu.
        /// </summary>
        internal static string Menu_Project_DesignDeliverables {
            get {
                return ResourceManager.GetString("Menu_Project_DesignDeliverables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design direct charge rate maintenance.
        /// </summary>
        internal static string Menu_Project_DesignDirectChargeRate {
            get {
                return ResourceManager.GetString("Menu_Project_DesignDirectChargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design direct cost rate maintenance.
        /// </summary>
        internal static string Menu_Project_DesignDirectCostRate {
            get {
                return ResourceManager.GetString("Menu_Project_DesignDirectCostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design indirect charge rate maintenance.
        /// </summary>
        internal static string Menu_Project_DesignIndirectChargeRate {
            get {
                return ResourceManager.GetString("Menu_Project_DesignIndirectChargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design indirect cost rate maintenance.
        /// </summary>
        internal static string Menu_Project_DesignIndirectCostRate {
            get {
                return ResourceManager.GetString("Menu_Project_DesignIndirectCostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design progress maintenance menu.
        /// </summary>
        internal static string Menu_Project_DesignProgress {
            get {
                return ResourceManager.GetString("Menu_Project_DesignProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design progress distribution maintenance menu.
        /// </summary>
        internal static string Menu_Project_DesignProgressDistribution {
            get {
                return ResourceManager.GetString("Menu_Project_DesignProgressDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Distribution.
        /// </summary>
        internal static string Menu_Project_DesignProgressDistribution_Title {
            get {
                return ResourceManager.GetString("Menu_Project_DesignProgressDistribution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design resource allocation menu.
        /// </summary>
        internal static string Menu_Project_DesignResourceAllocation {
            get {
                return ResourceManager.GetString("Menu_Project_DesignResourceAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design deliverable status maintenance menu.
        /// </summary>
        internal static string Menu_Project_DesignStatuses {
            get {
                return ResourceManager.GetString("Menu_Project_DesignStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project design variation maintenance menu.
        /// </summary>
        internal static string Menu_Project_DesignVariation {
            get {
                return ResourceManager.GetString("Menu_Project_DesignVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query design variation breakdown.
        /// </summary>
        internal static string Menu_Project_DesignVariationQuery {
            get {
                return ResourceManager.GetString("Menu_Project_DesignVariationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline description a.k.a package name maintenance menu.
        /// </summary>
        internal static string Menu_Project_DisciplineDescription {
            get {
                return ResourceManager.GetString("Menu_Project_DisciplineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project POs maintenance menu read/write.
        /// </summary>
        internal static string Menu_Project_EXO_AllPO {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_AllPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project EXO jobs permissions maintenance menu.
        /// </summary>
        internal static string Menu_Project_EXO_JobPermission {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_JobPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project EXO jobs maintenance menu.
        /// </summary>
        internal static string Menu_Project_EXO_Jobs {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all EXO job changes from BluePrints.
        /// </summary>
        internal static string Menu_Project_EXO_JobsHistory {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_JobsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock item sell prices for rates job.
        /// </summary>
        internal static string Menu_Project_EXO_SellPrices {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_SellPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project EXO timesheet maintenance menu.
        /// </summary>
        internal static string Menu_Project_EXO_Timesheets {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_Timesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project EXO timesheet query menu.
        /// </summary>
        internal static string Menu_Project_EXO_Timesheets_Query {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_Timesheets_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project EXO transactions maintenance menu read/write.
        /// </summary>
        internal static string Menu_Project_EXO_Transactions {
            get {
                return ResourceManager.GetString("Menu_Project_EXO_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project forecast menu.
        /// </summary>
        internal static string Menu_Project_Forecast {
            get {
                return ResourceManager.GetString("Menu_Project_Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project all EAC view.
        /// </summary>
        internal static string Menu_Project_Forecast_AllEAC {
            get {
                return ResourceManager.GetString("Menu_Project_Forecast_AllEAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project claims menu.
        /// </summary>
        internal static string Menu_Project_Forecast_Claims {
            get {
                return ResourceManager.GetString("Menu_Project_Forecast_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project equipment hire PO forecast maintenance menu.
        /// </summary>
        internal static string Menu_Project_Forecast_Flat_PO {
            get {
                return ResourceManager.GetString("Menu_Project_Forecast_Flat_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project indirect forecast maintenance menu.
        /// </summary>
        internal static string Menu_Project_Forecast_Indirect {
            get {
                return ResourceManager.GetString("Menu_Project_Forecast_Indirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project PO forecast maintenance menu.
        /// </summary>
        internal static string Menu_Project_Forecast_PO {
            get {
                return ResourceManager.GetString("Menu_Project_Forecast_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project holidays maintenance.
        /// </summary>
        internal static string Menu_Project_Holidays {
            get {
                return ResourceManager.GetString("Menu_Project_Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project HSE maintenance.
        /// </summary>
        internal static string Menu_Project_HSE {
            get {
                return ResourceManager.GetString("Menu_Project_HSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project HSE report maintenance.
        /// </summary>
        internal static string Menu_Project_HSEReport {
            get {
                return ResourceManager.GetString("Menu_Project_HSEReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project meetings maintenance.
        /// </summary>
        internal static string Menu_Project_Meetings {
            get {
                return ResourceManager.GetString("Menu_Project_Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project meeting types maintenance.
        /// </summary>
        internal static string Menu_Project_MeetingTypes {
            get {
                return ResourceManager.GetString("Menu_Project_MeetingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project pipelines maintenance menu.
        /// </summary>
        internal static string Menu_Project_Pipelines {
            get {
                return ResourceManager.GetString("Menu_Project_Pipelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project change register maintenance.
        /// </summary>
        internal static string Menu_Project_Register_Change {
            get {
                return ResourceManager.GetString("Menu_Project_Register_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Clarification Register.
        /// </summary>
        internal static string Menu_Project_Register_Clarification {
            get {
                return ResourceManager.GetString("Menu_Project_Register_Clarification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project hold register maintenance.
        /// </summary>
        internal static string Menu_Project_Register_Hold {
            get {
                return ResourceManager.GetString("Menu_Project_Register_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project issue register maintenance.
        /// </summary>
        internal static string Menu_Project_Register_Issue {
            get {
                return ResourceManager.GetString("Menu_Project_Register_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project lessons learned register maintenance.
        /// </summary>
        internal static string Menu_Project_Register_LessonsLearned {
            get {
                return ResourceManager.GetString("Menu_Project_Register_LessonsLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project non-conformance register maintenance.
        /// </summary>
        internal static string Menu_Project_Register_NonConformance {
            get {
                return ResourceManager.GetString("Menu_Project_Register_NonConformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project risk register maintenance.
        /// </summary>
        internal static string Menu_Project_Register_Risk {
            get {
                return ResourceManager.GetString("Menu_Project_Register_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project TQ register.
        /// </summary>
        internal static string Menu_Project_Register_TQ {
            get {
                return ResourceManager.GetString("Menu_Project_Register_TQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project studies maintenance.
        /// </summary>
        internal static string Menu_Project_Studies {
            get {
                return ResourceManager.GetString("Menu_Project_Studies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project subjobs maintenance menu.
        /// </summary>
        internal static string Menu_Project_Subjob {
            get {
                return ResourceManager.GetString("Menu_Project_Subjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project workpacks menu.
        /// </summary>
        internal static string Menu_Project_Workpacks {
            get {
                return ResourceManager.GetString("Menu_Project_Workpacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s timesheet review.
        /// </summary>
        internal static string Menu_ReviewTimesheet {
            get {
                return ResourceManager.GetString("Menu_ReviewTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles maintenance menu.
        /// </summary>
        internal static string Menu_Roles {
            get {
                return ResourceManager.GetString("Menu_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock code maintenance menu.
        /// </summary>
        internal static string Menu_StockCode {
            get {
                return ResourceManager.GetString("Menu_StockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock group maintenance menu.
        /// </summary>
        internal static string Menu_StockGroup {
            get {
                return ResourceManager.GetString("Menu_StockGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study type maintenance menu.
        /// </summary>
        internal static string Menu_StudyType {
            get {
                return ResourceManager.GetString("Menu_StudyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub prompt maintenance menu.
        /// </summary>
        internal static string Menu_SubPrompt {
            get {
                return ResourceManager.GetString("Menu_SubPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender profiles maintenance menu.
        /// </summary>
        internal static string Menu_TenderProfiles {
            get {
                return ResourceManager.GetString("Menu_TenderProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all Montreal EXO transactions from 2020 onwards.
        /// </summary>
        internal static string Menu_TransactionsMontreal2020ToDate {
            get {
                return ResourceManager.GetString("Menu_TransactionsMontreal2020ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all Montreal EXO transactions year to date.
        /// </summary>
        internal static string Menu_TransactionsMontrealYearToDate {
            get {
                return ResourceManager.GetString("Menu_TransactionsMontrealYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all Perth EXO transactions from 2020 onwards.
        /// </summary>
        internal static string Menu_TransactionsPerth2020ToDate {
            get {
                return ResourceManager.GetString("Menu_TransactionsPerth2020ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all Perth EXO transactions from 2020 onwards.
        /// </summary>
        internal static string Menu_TransactionsPerthYearToDate {
            get {
                return ResourceManager.GetString("Menu_TransactionsPerthYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all USA EXO transactions year to date.
        /// </summary>
        internal static string Menu_TransactionsUSAYearToDate {
            get {
                return ResourceManager.GetString("Menu_TransactionsUSAYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOMs maintenance menu.
        /// </summary>
        internal static string Menu_UOMs {
            get {
                return ResourceManager.GetString("Menu_UOMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Menu_User_Title {
            get {
                return ResourceManager.GetString("Menu_User_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s dashboard menu.
        /// </summary>
        internal static string Menu_UserDashboard {
            get {
                return ResourceManager.GetString("Menu_UserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s deliverables menu.
        /// </summary>
        internal static string Menu_UserDeliverables {
            get {
                return ResourceManager.GetString("Menu_UserDeliverables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users maintenance menu.
        /// </summary>
        internal static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s timesheet menu.
        /// </summary>
        internal static string Menu_UserTimesheet {
            get {
                return ResourceManager.GetString("Menu_UserTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow editing uncommitted costs on construction.
        /// </summary>
        internal static string Permission_ConstructionUncommitted {
            get {
                return ResourceManager.GetString("Permission_ConstructionUncommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book time for other users.
        /// </summary>
        internal static string Permission_DesignDeliverables_BookTimeForOthers {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_BookTimeForOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow moving data date forward and backward.
        /// </summary>
        internal static string Permission_DesignDeliverables_CanDateBackwardForward {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_CanDateBackwardForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalise deliverable&apos;s internal and client numbers.
        /// </summary>
        internal static string Permission_DesignDeliverables_FinaliseNumbers {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_FinaliseNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve deliverable&apos;s internal and client numbers.
        /// </summary>
        internal static string Permission_DesignDeliverables_InternalNumbersApproval {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_InternalNumbersApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapprove deliverable&apos;s internal and client numbers.
        /// </summary>
        internal static string Permission_DesignDeliverables_InternalNumbersUnapproval {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_InternalNumbersUnapproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use previous week&apos;s date for progress.
        /// </summary>
        internal static string Permission_DesignDeliverables_ProgressPreviousWeeksDate {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_ProgressPreviousWeeksDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update deliverable&apos;s progress by gate/status.
        /// </summary>
        internal static string Permission_DesignDeliverables_UpdateProgressByStatus {
            get {
                return ResourceManager.GetString("Permission_DesignDeliverables_UpdateProgressByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change budget in EXO.
        /// </summary>
        internal static string Permission_EXO_ChangeBudget {
            get {
                return ResourceManager.GetString("Permission_EXO_ChangeBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow commit to EXO.
        /// </summary>
        internal static string Permission_EXO_Timesheets_Commit {
            get {
                return ResourceManager.GetString("Permission_EXO_Timesheets_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow changing quantity in EXO transaction.
        /// </summary>
        internal static string Permission_EXO_Transactions_ChangeQuantity {
            get {
                return ResourceManager.GetString("Permission_EXO_Transactions_ChangeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show costs on EXO transactions.
        /// </summary>
        internal static string Permission_EXO_Transactions_ShowCosts {
            get {
                return ResourceManager.GetString("Permission_EXO_Transactions_ShowCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubmit EXO timesheet.
        /// </summary>
        internal static string Permission_EXO_UserTimesheet_Unsubmit {
            get {
                return ResourceManager.GetString("Permission_EXO_UserTimesheet_Unsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit previous EAC.
        /// </summary>
        internal static string Permission_Forecast_EditPreviousEAC {
            get {
                return ResourceManager.GetString("Permission_Forecast_EditPreviousEAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forecast data date forward and backward.
        /// </summary>
        internal static string Permission_Forecast_MoveDataDate {
            get {
                return ResourceManager.GetString("Permission_Forecast_MoveDataDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save forecast current EAC.
        /// </summary>
        internal static string Permission_Forecast_SaveEAC {
            get {
                return ResourceManager.GetString("Permission_Forecast_SaveEAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save forecast project budget.
        /// </summary>
        internal static string Permission_Forecast_SaveProjectBudget {
            get {
                return ResourceManager.GetString("Permission_Forecast_SaveProjectBudget", resourceCulture);
            }
        }
    }
}
