//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PermissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.PermissionResources", typeof(PermissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to book time for others.
        /// </summary>
        internal static string BookOtherTime {
            get {
                return ResourceManager.GetString("BookOtherTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage areas.
        /// </summary>
        internal static string ManageArea {
            get {
                return ResourceManager.GetString("ManageArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage baselines.
        /// </summary>
        internal static string ManageBaseline {
            get {
                return ResourceManager.GetString("ManageBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage budget.
        /// </summary>
        internal static string ManageBudget {
            get {
                return ResourceManager.GetString("ManageBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage commodities.
        /// </summary>
        internal static string ManageCommodity {
            get {
                return ResourceManager.GetString("ManageCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage deliverable statuses.
        /// </summary>
        internal static string ManageDeliverableStatuses {
            get {
                return ResourceManager.GetString("ManageDeliverableStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage departments.
        /// </summary>
        internal static string ManageDepartment {
            get {
                return ResourceManager.GetString("ManageDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage disciplines.
        /// </summary>
        internal static string ManageDiscipline {
            get {
                return ResourceManager.GetString("ManageDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage document types.
        /// </summary>
        internal static string ManageDocType {
            get {
                return ResourceManager.GetString("ManageDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage estimations.
        /// </summary>
        internal static string ManageEstimation {
            get {
                return ResourceManager.GetString("ManageEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage S-Curve holidays.
        /// </summary>
        internal static string ManageHoliday {
            get {
                return ResourceManager.GetString("ManageHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage office.
        /// </summary>
        internal static string ManageOffice {
            get {
                return ResourceManager.GetString("ManageOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage phase.
        /// </summary>
        internal static string ManagePhase {
            get {
                return ResourceManager.GetString("ManagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage progress.
        /// </summary>
        internal static string ManageProgress {
            get {
                return ResourceManager.GetString("ManageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage progress distribution.
        /// </summary>
        internal static string ManageProgressDistribution {
            get {
                return ResourceManager.GetString("ManageProgressDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage projects.
        /// </summary>
        internal static string ManageProject {
            get {
                return ResourceManager.GetString("ManageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage rates.
        /// </summary>
        internal static string ManageRate {
            get {
                return ResourceManager.GetString("ManageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage registers.
        /// </summary>
        internal static string ManageRegisters {
            get {
                return ResourceManager.GetString("ManageRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage roles.
        /// </summary>
        internal static string ManageRole {
            get {
                return ResourceManager.GetString("ManageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage stock codes.
        /// </summary>
        internal static string ManageStockCode {
            get {
                return ResourceManager.GetString("ManageStockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage study types.
        /// </summary>
        internal static string ManageStudyType {
            get {
                return ResourceManager.GetString("ManageStudyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage subjobs.
        /// </summary>
        internal static string ManageSubjob {
            get {
                return ResourceManager.GetString("ManageSubjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage other users.
        /// </summary>
        internal static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage variation.
        /// </summary>
        internal static string ManageVariation {
            get {
                return ResourceManager.GetString("ManageVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to manage workpack.
        /// </summary>
        internal static string ManageWorkpack {
            get {
                return ResourceManager.GetString("ManageWorkpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to update progress percentage by deliverable status.
        /// </summary>
        internal static string ProgressUpdatePercentageByStatus {
            get {
                return ResourceManager.GetString("ProgressUpdatePercentageByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to standardize subjobs in exo.
        /// </summary>
        internal static string StandardizeSubJobs {
            get {
                return ResourceManager.GetString("StandardizeSubJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to view dashboard.
        /// </summary>
        internal static string ViewDashboard {
            get {
                return ResourceManager.GetString("ViewDashboard", resourceCulture);
            }
        }
    }
}
