//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PermissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.PermissionResources", typeof(PermissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve internal and client numbers.
        /// </summary>
        internal static string ApproveInternalNumbers {
            get {
                return ResourceManager.GetString("ApproveInternalNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book time for others.
        /// </summary>
        internal static string BookOtherTime {
            get {
                return ResourceManager.GetString("BookOtherTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forecast data date forward.
        /// </summary>
        internal static string CanForwardDataDate {
            get {
                return ResourceManager.GetString("CanForwardDataDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forecast data date backward.
        /// </summary>
        internal static string CanRewindDataDate {
            get {
                return ResourceManager.GetString("CanRewindDataDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change project budget.
        /// </summary>
        internal static string ChangeBudget {
            get {
                return ResourceManager.GetString("ChangeBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalise internal and client numbers.
        /// </summary>
        internal static string FinaliseNumbers {
            get {
                return ResourceManager.GetString("FinaliseNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage areas.
        /// </summary>
        internal static string ManageArea {
            get {
                return ResourceManager.GetString("ManageArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage baselines.
        /// </summary>
        internal static string ManageBaseline {
            get {
                return ResourceManager.GetString("ManageBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage commodities.
        /// </summary>
        internal static string ManageCommodity {
            get {
                return ResourceManager.GetString("ManageCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage cost rates.
        /// </summary>
        internal static string ManageCostRate {
            get {
                return ResourceManager.GetString("ManageCostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage deliverable statuses.
        /// </summary>
        internal static string ManageDeliverableStatuses {
            get {
                return ResourceManager.GetString("ManageDeliverableStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage departments.
        /// </summary>
        internal static string ManageDepartment {
            get {
                return ResourceManager.GetString("ManageDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage disciplines.
        /// </summary>
        internal static string ManageDiscipline {
            get {
                return ResourceManager.GetString("ManageDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage document types.
        /// </summary>
        internal static string ManageDocType {
            get {
                return ResourceManager.GetString("ManageDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage estimations.
        /// </summary>
        internal static string ManageEstimation {
            get {
                return ResourceManager.GetString("ManageEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage exo users (Confidential Information).
        /// </summary>
        internal static string ManageEXOUsers {
            get {
                return ResourceManager.GetString("ManageEXOUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage forecast.
        /// </summary>
        internal static string ManageForecast {
            get {
                return ResourceManager.GetString("ManageForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage S-Curve holidays.
        /// </summary>
        internal static string ManageHoliday {
            get {
                return ResourceManager.GetString("ManageHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage construction job setup.
        /// </summary>
        internal static string ManageJobSetup {
            get {
                return ResourceManager.GetString("ManageJobSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage office.
        /// </summary>
        internal static string ManageOffice {
            get {
                return ResourceManager.GetString("ManageOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage phase.
        /// </summary>
        internal static string ManagePhase {
            get {
                return ResourceManager.GetString("ManagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage progress.
        /// </summary>
        internal static string ManageProgress {
            get {
                return ResourceManager.GetString("ManageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage progress distribution.
        /// </summary>
        internal static string ManageProgressDistribution {
            get {
                return ResourceManager.GetString("ManageProgressDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage projects.
        /// </summary>
        internal static string ManageProject {
            get {
                return ResourceManager.GetString("ManageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage chargeout rates.
        /// </summary>
        internal static string ManageRate {
            get {
                return ResourceManager.GetString("ManageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage registers.
        /// </summary>
        internal static string ManageRegisters {
            get {
                return ResourceManager.GetString("ManageRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string ManageRole {
            get {
                return ResourceManager.GetString("ManageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage stock codes.
        /// </summary>
        internal static string ManageStockCode {
            get {
                return ResourceManager.GetString("ManageStockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage study types.
        /// </summary>
        internal static string ManageStudyType {
            get {
                return ResourceManager.GetString("ManageStudyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage subjobs.
        /// </summary>
        internal static string ManageSubjob {
            get {
                return ResourceManager.GetString("ManageSubjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage tender profile.
        /// </summary>
        internal static string ManageTenderProfile {
            get {
                return ResourceManager.GetString("ManageTenderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage transactions.
        /// </summary>
        internal static string ManageTransactions {
            get {
                return ResourceManager.GetString("ManageTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage other users.
        /// </summary>
        internal static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage variation.
        /// </summary>
        internal static string ManageVariation {
            get {
                return ResourceManager.GetString("ManageVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage variation register.
        /// </summary>
        internal static string ManageVariationRegister {
            get {
                return ResourceManager.GetString("ManageVariationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage workpack.
        /// </summary>
        internal static string ManageWorkpack {
            get {
                return ResourceManager.GetString("ManageWorkpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update progress percentage by deliverable status.
        /// </summary>
        internal static string ProgressUpdatePercentageByStatus {
            get {
                return ResourceManager.GetString("ProgressUpdatePercentageByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save forecast EAC.
        /// </summary>
        internal static string SaveEAC {
            get {
                return ResourceManager.GetString("SaveEAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardize subjobs in exo.
        /// </summary>
        internal static string StandardizeSubJobs {
            get {
                return ResourceManager.GetString("StandardizeSubJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify internal and client numbers.
        /// </summary>
        internal static string UnapproveInternalNumbers {
            get {
                return ResourceManager.GetString("UnapproveInternalNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View dashboard.
        /// </summary>
        internal static string ViewDashboard {
            get {
                return ResourceManager.GetString("ViewDashboard", resourceCulture);
            }
        }
    }
}
