//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrints.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserPreferences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserPreferences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrints.Common.Resources.UserPreferences", typeof(UserPreferences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow summary to be calculated for every update.
        /// </summary>
        internal static string DesignProgress_AllowSummaryUpdate {
            get {
                return ResourceManager.GetString("DesignProgress_AllowSummaryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is design timesheet in database foreign.
        /// </summary>
        internal static string EXO_DesignTimeSheetOfficeIsForeign {
            get {
                return ResourceManager.GetString("EXO_DesignTimeSheetOfficeIsForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter actual by selected PO line(s) in PO view.
        /// </summary>
        internal static string EXO_POUseFilter {
            get {
                return ResourceManager.GetString("EXO_POUseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preload all transactions instead of streaming from server.
        /// </summary>
        internal static string EXO_PreloadTransactions {
            get {
                return ResourceManager.GetString("EXO_PreloadTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide summary on forecast.
        /// </summary>
        internal static string Forecast_AutoHideSummary {
            get {
                return ResourceManager.GetString("Forecast_AutoHideSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show actuals on forecast.
        /// </summary>
        internal static string Forecast_ShowActuals {
            get {
                return ResourceManager.GetString("Forecast_ShowActuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show user deliverables list on startup.
        /// </summary>
        internal static string Global_HideUserDeliverablesOnStartup {
            get {
                return ResourceManager.GetString("Global_HideUserDeliverablesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string PreferenceFalseValue {
            get {
                return ResourceManager.GetString("PreferenceFalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string PreferenceTrueValue {
            get {
                return ResourceManager.GetString("PreferenceTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark burned S-Curve against budget.
        /// </summary>
        internal static string SCurve_BurnedBenchmarkedAgainstBudget {
            get {
                return ResourceManager.GetString("SCurve_BurnedBenchmarkedAgainstBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark current S-Curve against budget.
        /// </summary>
        internal static string SCurve_CurrentBenchmarkedAgainstBudget {
            get {
                return ResourceManager.GetString("SCurve_CurrentBenchmarkedAgainstBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark earned S-Curve against budget.
        /// </summary>
        internal static string SCurve_EarnedBenchmarkedAgainstBudget {
            get {
                return ResourceManager.GetString("SCurve_EarnedBenchmarkedAgainstBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark remaining S-Cureve against budget.
        /// </summary>
        internal static string SCurve_RemainingBenchmarkedAgainstBudget {
            get {
                return ResourceManager.GetString("SCurve_RemainingBenchmarkedAgainstBudget", resourceCulture);
            }
        }
    }
}
